# Generated by Django 5.1.2 on 2024-10-22 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="check_in_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="check_out_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_guest",
                to="mainapp.guests",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_room",
                to="mainapp.rooms",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
