# Generated by Django 5.1.2 on 2024-10-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_transactions_check_in_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="check_in_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="check_out_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_date",
            field=models.DateTimeField(),
        ),
    ]
